version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx1024m

    steps:
      - checkout

      - run:
          command: |
              git submodule sync --recursive
              git submodule update --init --recursive
              cd libdivide4j
              mvn clean install -DskipTests

      
      - run:
          command: |
              cd rings.scaladsl
              sbt test
